"""Registry of generated artifacts + the ``docs/generated/README.md`` index.

Every artifact written to ``docs/generated/`` must be declared in
:func:`artifacts`. The manifest test asserts the directory contents match the
registry exactly, so a generator that is renamed or stops running turns into a
test failure instead of a silently rotting committed file.
"""

from __future__ import annotations

from dataclasses import dataclass

from tests.guardrail._common import GENERATED_DIR, with_header


@dataclass(frozen=True)
class Artifact:
    path: str  # relative to docs/generated/
    title: str
    description: str  # one line, CONTEXT.md vocabulary


def artifacts() -> list[Artifact]:
    """All generated artifacts, in the order they appear in the index."""
    return [
        Artifact(
            path="architecture.md",
            title="Component dependencies",
            description=(
                "Cross-component import graph computed from the real code via grimp, "
                "grouped by tier (Entrypoints → Core → Foundation)."
            ),
        ),
        Artifact(
            path="domain_model.md",
            title="Domain model",
            description=(
                "Class diagram of the domain dataclasses and Pydantic models, "
                "extracted statically from the modules listed in docs/architecture.toml."
            ),
        ),
        Artifact(
            path="metrics.md",
            title="Architecture metrics",
            description=(
                "Quantitative snapshot (coupling, cycles, size, complexity) with the hard "
                "budgets from docs/architecture.toml — the improving-vs-regressing signal."
            ),
        ),
        Artifact(
            path="metrics.json",
            title="Architecture metrics (machine-readable)",
            description=(
                "Same snapshot as JSON; its git history is the metric time series "
                "(`make metrics-history`)."
            ),
        ),
    ]


def render_index() -> str:
    lines = [
        "# Generated architecture docs",
        "",
        (
            "Everything in this directory is a **derived view of the source code** — "
            + "generated by `tests/guardrail/`, committed, and drift-checked in CI. If the "
            + "code changes shape, the committed view here disagrees with the corpus of "
            + "code and CI fails until it is reconciled: run `make diagrams` and commit "
            + "the result."
        ),
        "",
        "Do not edit these files by hand.",
        "",
        "## Artifacts",
        "",
        "| Artifact | What it shows |",
        "|---|---|",
    ]
    for a in artifacts():
        lines.append(f"| [{a.title}]({a.path}) | {a.description} |")
    lines += [
        "",
        "## Legend",
        "",
        "- `A --> B` in the component diagram: at least one real `import` from a module",
        "  in component A to a module in component B.",
        "- Tier subgraphs (Entrypoints / Core / Foundation): dependencies must only",
        "  point downward; enforced by import-linter (`pyproject.toml [tool.importlinter]`).",
        '- `Src "1" --> "0..*" Dst : field` in the domain model: class `Src` has a',
        "  field holding many `Dst`; `0..1` = optional, `1` = exactly one.",
        "",
        "## Sources of truth",
        "",
        "- [`docs/architecture.toml`](../architecture.toml) — components, tiers, and",
        "  which modules are scanned for domain models.",
        "- `pyproject.toml [tool.importlinter]` — the enforced directional contracts.",
        "- [`CONTEXT.md`](../../CONTEXT.md) — the domain vocabulary used in labels.",
        "- [`docs/adr/`](../adr/) — the decisions behind the architecture.",
        "",
        "## Regenerating",
        "",
        "```sh",
        "make diagrams   # = pytest tests/guardrail/ -q",
        "```",
        "",
        "Then commit the changes. The CI job `Diagram drift` fails when the committed",
        "files disagree with what the code generates.",
    ]
    return with_header("\n".join(lines) + "\n")


def generated_files() -> set[str]:
    """Relative paths of all files currently present under docs/generated/."""
    return {
        str(p.relative_to(GENERATED_DIR)) for p in sorted(GENERATED_DIR.rglob("*")) if p.is_file()
    }
