"""Regenerate the per-component drill-down pages (drift-checked in CI)."""

from __future__ import annotations

from tests.guardrail import _component_pages as cp
from tests.guardrail._common import load_architecture, write


def test_generate_component_pages() -> None:
    pages = cp.render_all()
    components = load_architecture()["components"]
    assert set(pages) == {f"components/{c}.md" for c in components}
    for relpath, content in pages.items():
        out = write(relpath, content)
        assert out.exists()
        assert content.startswith("<!-- AUTOGENERATED")


def test_every_component_has_a_description() -> None:
    arch = load_architecture()
    docs = arch.get("component_docs", {})
    missing = sorted(c for c in arch["components"] if not docs.get(c))
    assert not missing, f"components missing a [component_docs] one-liner: {missing}"
